---
helpforge_ip: "192.168.56.102"
mysql_root_password: "80ffabd9008a3ff9f016e7c7325c2280"
glpi_db_name: "glpidb"
glpi_db_user: "glpiuser"
glpi_db_password: "HelpForge_DB_Backend_2024!"
glpi_checksum: ""
techops_name: "techops"
techops_password: "TechOps_HelpForge24"
user_flag: "FLAG{917b43b3f6ec820a25ed2cb465426259}"
root_flag: "FLAG{d5a31615c10bb7671aa2f4bbbd161f05}"
disable_ipv6: false
